### ISSUE TITLE
Comparing NN

### ISSUE THREAD

**Issue by roo27666** [OverLordGoldDragon/see-rnn#45]
I apologise I know this isn't how one contacts developers. If you have time I need to discussed with you about RNN in private session. Could you please provide me your e-mail or any app that I can talk with you. Thank you so much

**Comment by OverLordGoldDragon** [comment]
Most developers myself included don't take private requests, but you're free to ask a focused question on [Stack Exchange](https://ai.stackexchange.com/), [r/MachineLearning](https://www.reddit.com/r/MachineLearning/), or here with a temporary account.

**Comment by roo27666** [comment]
Thank you for your response. I have two Relu models (NN) and I want to compare between them as you mentioned previously in Visualizing weights, Interpreting weights and Models Validation Performance. 

How can we tranlate the concept by Python, I mean in programming . I find it very difficult and complex.

**Comment by roo27666** [comment]
I write here because I need to get your point directly. Thank

**Comment by OverLordGoldDragon** [comment]
Seems like you should take an introductory course in ML or Python; neither I can help with. You can use `see_rnn` to visualize weights, activations, or gradients with appropriate functions as shown in examples, and functions come with docstrings (e.g. `help(get_gradients)` that help to use them. For further help I defer to same sources and additionally [r/learnmachinelearning](https://www.reddit.com/r/learnmachinelearning/).

**Comment by roo27666** [comment]
Thanks . I  am working in a huge project now. but I confused in this point. Is the code of Visualizing weights, Interpreting weights and Models Validation Performance in this project? I can't find it

**Comment by OverLordGoldDragon** [comment]
There is no demo code beyond README and `sandbox.py`, but what you mention seems familiar though I can't recall exactly - I'd guess it's from a StackOverflow answer of mine. Where'd you read "Visualizing weights, Interpreting..."?

**Comment by roo27666** [comment]
yes from https://stackoverflow.com/questions/58401393/how-can-i-compare-weights-of-different-keras-models

**Comment by OverLordGoldDragon** [comment]
Right. These were outline possible goals; the code for all that would be an entire project.

**Comment by roo27666** [comment]
Sorry I didn't get it. Which files or line that helps me. I really confused. Thank you so much

**Comment by OverLordGoldDragon** [comment]
I meant there is no code for what I wrote in that answer.

**Comment by roo27666** [comment]
Thank you. 
Do you know how can we find number of hidden node, # of layers and minimum weight? 
in Relu model
