### ISSUE TITLE
How to cite your work

### ISSUE THREAD

**Issue by wanggis** [OverLordGoldDragon/see-rnn#52]
Hi, there.
I really appreciate your work , and it helped me solve a big problem in my research work.
Now I'm writing paper, and I  want to cite your work to express my gratitude. 
So how do I cite your work? Or have you published academic papers  based on this GitRepo？
I am looking forward for your reply

**Comment by OverLordGoldDragon** [comment]
Glad to hear my work has helped. I've added a [How to cite](https://github.com/OverLordGoldDragon/see-rnn#how-to-cite).

Thank you.
