### ISSUE TITLE
Installation support needed

### ISSUE THREAD

**Issue by DaleMYChen** [OverLordGoldDragon/see-rnn#55]
First of all many Thanks for this repo. I have been attempting to extract the partial derivatives dc_t/dc_0 in LSTM training but this quantity quickly vanishes at t increases. see_rnn is apparently a great alternative to use for visualising the vanishing gradients in RNN-class models and I would love to try it out.

Installation with ```pip install git+https://github.com/OverLordGoldDragon/see-rnn``` produces the following error:
```
ERROR: Command errored out with exit status 1:
   command: git version
       cwd: None
  Complete output (2 lines):
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

I have used ```pip install see_rnn``` instead, however when I tried the example under the Usage section I am receiving an error message for ```cannot import get_gradients```. 
In fact none of the functions in the command
```from see_rnn import get_gradients, features_0D, features_1D, features_2D``` can be found in the installed package or [here](https://github.com/OverLordGoldDragon/see-rnn/tree/master/see_rnn). I would like some help with this part. Thanks in advance!

**Comment by OverLordGoldDragon** [comment]
Hello, glad you like the repo.

I'm not reproducing your error. Can you install other libraries with `pip install`? If yes, try asking on SO. Worst case, simply cloning the repository will work, along manually installing [requirements](https://github.com/OverLordGoldDragon/see-rnn/blob/master/requirements.txt) (plus TF for full functionality).

**Comment by DaleMYChen** [comment]
> Hello, glad you like the repo.
> 
> I'm not reproducing your error. Can you install other libraries with `pip install`? If yes, try asking on SO. Worst case, simply cloning the repository will work, along manually installing [requirements](https://github.com/OverLordGoldDragon/see-rnn/blob/master/requirements.txt) (plus TF for full functionality).

Realised that it's just a minor issue: a parent file named 'see-rnn' is installed, containing 'see_rnn'. Renaming it to 'See_rnn', calling the imports by 
```
import See_rnn.see_rnn as see_rnn
from See_rnn.see_rnn import get_gradients, features_0D, features_1D, features_2D
```
will do.

Just an additional point: in the Usage example the kwarg ```xy_ticks``` of features_1D should be ```show_xy_ticks```

**Comment by OverLordGoldDragon** [comment]
```
import See_rnn.see_rnn as see_rnn
```
Never seen this as necessary, but guess it's an option.

> xy_ticks of features_1D should be show_xy_ticks

Thanks, fixed.

Issue looks resolved, closing.
