### ISSUE TITLE
give visibility to _watch_layer_outputs

### ISSUE THREAD

**Issue by Juan-estudiante-uam** [OverLordGoldDragon/see-rnn#58]
Hi @OverLordGoldDragon, i made use of `_watch_layer_outputs`  and with some changes in your code I managed to visualize a custom made RNN using Keras Model Subclassing API. While your implementation through a Wrapper helped me a lot, I did not notice the function even existed but after some time. Since the function is not called by any other one, perhaps it could be included in the `README.md` so other people can make use of it. Thanks for the awesome work, I could visually check my vanishing gradient problem!! 
![gradients2](https://user-images.githubusercontent.com/74192521/205179528-20f19428-2cfe-4aef-9dfd-ea14ef3376a0.png)

**Comment by OverLordGoldDragon** [comment]
Thanks for the feedback. Though, I no longer actively maintain this repository.
