### ISSUE TITLE
cannot import name error

### ISSUE THREAD

**Issue by yutapatio** [OverLordGoldDragon/see-rnn#9]
Hi, thank you very much for the great work!
I tried to put my original Python script, then encountered the error below.
cannot import name 'get_rnn_gradients' from 'see_rnn' (C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\see_rnn\__init__.py)

How should I solve this error?

Regards,

**Comment by OverLordGoldDragon** [comment]
Hello,

Is that the actual error trace? `see_rnn_init_.py` isn't a file in this repository. The best way to install is to just clone the repo or download the zip file, and place the `see_rnn` folder in a directory where Python can find it (e.g. is on PYTHONPATH).

**Comment by yutapatio** [comment]
Hello, Thank you very much for quick prompt. However, unfortunately, it still does not work.
I did the way which you mentioned, but got the same error message.
cannot import name 'get_rnn_gradients' from 'see_rnn' (C:\Users\username\AppData\Local\Programs\Python\Python37\see_rnn\__init__.py)

**Comment by OverLordGoldDragon** [comment]
My mistake. `get_rnn_gradients` has been deprecated in favor of general-purpose [`get_layer_gradients`](https://github.com/OverLordGoldDragon/see-rnn/blob/master/see_rnn/inspect_gen.py#L47); I will update the README - thanks for raising this Issue. Try `from see_rnn import get_layer_gradients`.

**Comment by yutapatio** [comment]
Thank you for solving the issue.
